apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-managerDBApp
  name: service-managerDBApp-deployment
  namespace: sealos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-managerDBApp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: service-managerDBApp
    spec:
      containers:
        - command:
            - /manager
          args:
            - "-kubeconfig=/config/kubeconfig"
            - "-port=8429"
          image: bearslyricattack/service-managerdbapp:latest
          imagePullPolicy: Always
          name: service-vlogs
          ports:
            - containerPort: 8429
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 5m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /config/kubeconfig
              subPath: kubeconfig
              name: kubeconfig-vol
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: kubeconfig-vol
          configMap:
            name: admin-kubeconfig
            defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-managerDBApp
  name: service-managerDBApp
  namespace: sealos
spec:
  ports:
    - name: http
      port: 8429
      protocol: TCP
      targetPort: 8429
  selector:
    app: service-managerDBApp